// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AppendEvent(ctx context.Context, arg AppendEventParams) error
	AppendToOutbox(ctx context.Context, arg AppendToOutboxParams) error
	DeleteOutboxEvent(ctx context.Context, id uuid.UUID) error
	GetEvents(ctx context.Context, aggregateID uuid.UUID) ([]GetEventsRow, error)
	GetOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
}

var _ Querier = (*Queries)(nil)
