// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: balances.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertBalanceUpdate = `-- name: InsertBalanceUpdate :exec
INSERT INTO balances_projection (id, account_id, currency, amount, value_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type InsertBalanceUpdateParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Currency  string    `json:"currency"`
	Amount    string    `json:"amount"`
	ValueDate time.Time `json:"value_date"`
}

func (q *Queries) InsertBalanceUpdate(ctx context.Context, arg InsertBalanceUpdateParams) error {
	_, err := q.db.ExecContext(ctx, insertBalanceUpdate,
		arg.ID,
		arg.AccountID,
		arg.Currency,
		arg.Amount,
		arg.ValueDate,
	)
	return err
}
