// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type BalancesProjection struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Currency  string    `json:"currency"`
	Amount    string    `json:"amount"`
	UserID    string    `json:"user_id"`
	ValueDate time.Time `json:"value_date"`
	CreatedAt time.Time `json:"created_at"`
	Origin    string    `json:"origin"`
}
