// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAccountDistributions(ctx context.Context, accountID uuid.UUID) ([]GetAccountDistributionsRow, error)
	GetAllBalances(ctx context.Context) ([]GetAllBalancesRow, error)
	GetBalancesByAccount(ctx context.Context, accountID uuid.UUID) ([]GetBalancesByAccountRow, error)
	InsertBalanceUpdate(ctx context.Context, arg InsertBalanceUpdateParams) error
}

var _ Querier = (*Queries)(nil)
