// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	InsertBalanceUpdate(ctx context.Context, arg InsertBalanceUpdateParams) error
}

var _ Querier = (*Queries)(nil)
