// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type AccountsProjection struct {
	ID        uuid.UUID       `json:"id"`
	Balance   json.RawMessage `json:"balance"`
	CreatedAt sql.NullTime    `json:"created_at"`
	ClosedAt  sql.NullTime    `json:"closed_at"`
}
