// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	CloseAccount(ctx context.Context, arg CloseAccountParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	GetAccountBalanceForUpdate(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetAllAccounts(ctx context.Context) ([]AccountsProjection, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpsertPlaceholderAccount(ctx context.Context, arg UpsertPlaceholderAccountParams) error
}

var _ Querier = (*Queries)(nil)
