// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const closeAccount = `-- name: CloseAccount :exec
UPDATE accounts_projection
SET closed_at = $2
WHERE id = $1
`

type CloseAccountParams struct {
	ID       uuid.UUID    `json:"id"`
	ClosedAt sql.NullTime `json:"closed_at"`
}

func (q *Queries) CloseAccount(ctx context.Context, arg CloseAccountParams) error {
	_, err := q.db.ExecContext(ctx, closeAccount, arg.ID, arg.ClosedAt)
	return err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts_projection (id, name, created_at, balance)
VALUES ($1, $2, $3, '{}')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, created_at = EXCLUDED.created_at
`

type CreateAccountParams struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const getAccountBalanceForUpdate = `-- name: GetAccountBalanceForUpdate :one
SELECT balance 
FROM accounts_projection 
WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountBalanceForUpdate(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalanceForUpdate, id)
	var balance json.RawMessage
	err := row.Scan(&balance)
	return balance, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, name, balance, created_at, closed_at 
FROM accounts_projection
`

type GetAllAccountsRow struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Balance   json.RawMessage `json:"balance"`
	CreatedAt sql.NullTime    `json:"created_at"`
	ClosedAt  sql.NullTime    `json:"closed_at"`
}

func (q *Queries) GetAllAccounts(ctx context.Context) ([]GetAllAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAccountsRow
	for rows.Next() {
		var i GetAllAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Balance,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts_projection 
SET balance = $2 
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID       `json:"id"`
	Balance json.RawMessage `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}

const updateAccountName = `-- name: UpdateAccountName :exec
UPDATE accounts_projection
SET name = $2
WHERE id = $1
`

type UpdateAccountNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountName, arg.ID, arg.Name)
	return err
}

const upsertPlaceholderAccount = `-- name: UpsertPlaceholderAccount :exec
INSERT INTO accounts_projection (id, name, balance) 
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type UpsertPlaceholderAccountParams struct {
	ID      uuid.UUID       `json:"id"`
	Name    string          `json:"name"`
	Balance json.RawMessage `json:"balance"`
}

func (q *Queries) UpsertPlaceholderAccount(ctx context.Context, arg UpsertPlaceholderAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlaceholderAccount, arg.ID, arg.Name, arg.Balance)
	return err
}
