// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: balance_updates.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAccountDistributions = `-- name: GetAccountDistributions :many
SELECT 
    id, account_id, currency, amount, user_id, value_date,
    SUM(CASE WHEN user_id = 'system' THEN amount ELSE 0 END) OVER (PARTITION BY account_id, currency ORDER BY value_date ASC, id ASC)::TEXT as system_amount,
    SUM(CASE WHEN user_id != 'system' THEN amount ELSE 0 END) OVER (PARTITION BY account_id, currency ORDER BY value_date ASC, id ASC)::TEXT as other_amount
FROM balance_updates
WHERE account_id = $1 AND origin = 'movement' AND (balance_type = $2 OR $2 = '')
ORDER BY value_date DESC, id DESC
`

type GetAccountDistributionsParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	BalanceType string    `json:"balance_type"`
}

type GetAccountDistributionsRow struct {
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
	Currency     string    `json:"currency"`
	Amount       string    `json:"amount"`
	UserID       string    `json:"user_id"`
	ValueDate    time.Time `json:"value_date"`
	SystemAmount string    `json:"system_amount"`
	OtherAmount  string    `json:"other_amount"`
}

func (q *Queries) GetAccountDistributions(ctx context.Context, arg GetAccountDistributionsParams) ([]GetAccountDistributionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccountDistributions, arg.AccountID, arg.BalanceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountDistributionsRow
	for rows.Next() {
		var i GetAccountDistributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Currency,
			&i.Amount,
			&i.UserID,
			&i.ValueDate,
			&i.SystemAmount,
			&i.OtherAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBalances = `-- name: GetAllBalances :many
SELECT DATE_TRUNC('month', value_date)::TIMESTAMP AS month, currency, SUM(amount)::TEXT AS amount
FROM balance_updates
WHERE (balance_type = $1 OR $1 = '')
GROUP BY month, currency
ORDER BY month DESC
`

type GetAllBalancesRow struct {
	Month    time.Time `json:"month"`
	Currency string    `json:"currency"`
	Amount   string    `json:"amount"`
}

func (q *Queries) GetAllBalances(ctx context.Context, balanceType string) ([]GetAllBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBalances, balanceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBalancesRow
	for rows.Next() {
		var i GetAllBalancesRow
		if err := rows.Scan(&i.Month, &i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalancesByAccount = `-- name: GetBalancesByAccount :many
SELECT DATE_TRUNC('month', value_date)::TIMESTAMP AS month, currency, SUM(amount)::TEXT AS amount
FROM balance_updates
WHERE account_id = $1 AND (balance_type = $2 OR $2 = '')
GROUP BY month, currency
ORDER BY month DESC
`

type GetBalancesByAccountParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	BalanceType string    `json:"balance_type"`
}

type GetBalancesByAccountRow struct {
	Month    time.Time `json:"month"`
	Currency string    `json:"currency"`
	Amount   string    `json:"amount"`
}

func (q *Queries) GetBalancesByAccount(ctx context.Context, arg GetBalancesByAccountParams) ([]GetBalancesByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, getBalancesByAccount, arg.AccountID, arg.BalanceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBalancesByAccountRow
	for rows.Next() {
		var i GetBalancesByAccountRow
		if err := rows.Scan(&i.Month, &i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBalanceUpdate = `-- name: InsertBalanceUpdate :exec
INSERT INTO balance_updates (id, account_id, currency, amount, user_id, origin, value_date, balance_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
`

type InsertBalanceUpdateParams struct {
	ID          uuid.UUID `json:"id"`
	AccountID   uuid.UUID `json:"account_id"`
	Currency    string    `json:"currency"`
	Amount      string    `json:"amount"`
	UserID      string    `json:"user_id"`
	Origin      string    `json:"origin"`
	ValueDate   time.Time `json:"value_date"`
	BalanceType string    `json:"balance_type"`
}

func (q *Queries) InsertBalanceUpdate(ctx context.Context, arg InsertBalanceUpdateParams) error {
	_, err := q.db.ExecContext(ctx, insertBalanceUpdate,
		arg.ID,
		arg.AccountID,
		arg.Currency,
		arg.Amount,
		arg.UserID,
		arg.Origin,
		arg.ValueDate,
		arg.BalanceType,
	)
	return err
}
