// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: budgets.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createBudget = `-- name: CreateBudget :exec
INSERT INTO budgets (id, name, data, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    data = EXCLUDED.data,
    updated_at = EXCLUDED.updated_at
`

type CreateBudgetParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Data      json.RawMessage `json:"data"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) error {
	_, err := q.db.ExecContext(ctx, createBudget,
		arg.ID,
		arg.Name,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets
WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, name, data, created_at, updated_at FROM budgets
WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgets = `-- name: GetBudgets :many
SELECT id, name, data, created_at, updated_at FROM budgets
ORDER BY name ASC
`

func (q *Queries) GetBudgets(ctx context.Context) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, getBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
