// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	CloseAccount(ctx context.Context, arg CloseAccountParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	GetAccountBalanceForUpdate(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetAccountDistributions(ctx context.Context, accountID uuid.UUID) ([]GetAccountDistributionsRow, error)
	GetAllAccounts(ctx context.Context) ([]GetAllAccountsRow, error)
	GetAllBalances(ctx context.Context) ([]GetAllBalancesRow, error)
	GetBalancesByAccount(ctx context.Context, accountID uuid.UUID) ([]GetBalancesByAccountRow, error)
	InsertBalanceUpdate(ctx context.Context, arg InsertBalanceUpdateParams) error
	ListTransactions(ctx context.Context) ([]ListTransactionsRow, error)
	ListTransactionsByAccount(ctx context.Context, accountID uuid.UUID) ([]ListTransactionsByAccountRow, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) error
	UpsertPlaceholderAccount(ctx context.Context, arg UpsertPlaceholderAccountParams) error
}

var _ Querier = (*Queries)(nil)
