// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transactions_projection.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
    id, account_id, transaction_type, amount, currency, category, description, happened_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateTransactionParams struct {
	ID              uuid.UUID `json:"id"`
	AccountID       uuid.UUID `json:"account_id"`
	TransactionType string    `json:"transaction_type"`
	Amount          string    `json:"amount"`
	Currency        string    `json:"currency"`
	Category        string    `json:"category"`
	Description     string    `json:"description"`
	HappenedAt      time.Time `json:"happened_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.ID,
		arg.AccountID,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.HappenedAt,
	)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT DISTINCT category FROM transactions ORDER BY category
`

func (q *Queries) ListCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
WITH distributions AS (
    SELECT
        id,
        SUM(CASE WHEN origin = 'movement' AND user_id = 'system' THEN amount ELSE 0 END) OVER (PARTITION BY account_id, currency ORDER BY value_date ASC, id ASC) as system_amount,
        SUM(CASE WHEN origin = 'movement' AND user_id != 'system' THEN amount ELSE 0 END) OVER (PARTITION BY account_id, currency ORDER BY value_date ASC, id ASC) as other_amount
    FROM balance_updates
)
SELECT
    t.id, t.account_id, t.transaction_type, t.amount, t.currency, t.category, t.description, t.happened_at, t.created_at,
    COALESCE(CASE WHEN (d.system_amount + d.other_amount) != 0 THEN (d.system_amount / (d.system_amount + d.other_amount))::TEXT ELSE '0' END, '0') as system_total_rate
FROM transactions t
LEFT JOIN distributions d ON t.id = d.id
ORDER BY t.happened_at DESC
`

type ListTransactionsRow struct {
	ID              uuid.UUID   `json:"id"`
	AccountID       uuid.UUID   `json:"account_id"`
	TransactionType string      `json:"transaction_type"`
	Amount          string      `json:"amount"`
	Currency        string      `json:"currency"`
	Category        string      `json:"category"`
	Description     string      `json:"description"`
	HappenedAt      time.Time   `json:"happened_at"`
	CreatedAt       time.Time   `json:"created_at"`
	SystemTotalRate interface{} `json:"system_total_rate"`
}

func (q *Queries) ListTransactions(ctx context.Context) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.HappenedAt,
			&i.CreatedAt,
			&i.SystemTotalRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
WITH distributions AS (
    SELECT
        id,
        SUM(CASE WHEN origin = 'movement' AND user_id = 'system' THEN amount ELSE 0 END) OVER (PARTITION BY account_id, currency ORDER BY value_date ASC, id ASC) as system_amount,
        SUM(CASE WHEN origin = 'movement' AND user_id != 'system' THEN amount ELSE 0 END) OVER (PARTITION BY account_id, currency ORDER BY value_date ASC, id ASC) as other_amount
    FROM balance_updates
)
SELECT
    t.id, t.account_id, t.transaction_type, t.amount, t.currency, t.category, t.description, t.happened_at, t.created_at,
    COALESCE(CASE WHEN (d.system_amount + d.other_amount) != 0 THEN (d.system_amount / (d.system_amount + d.other_amount))::TEXT ELSE '0' END, '0') as system_total_rate
FROM transactions t
LEFT JOIN distributions d ON t.id = d.id
WHERE t.account_id = $1
ORDER BY t.happened_at DESC
`

type ListTransactionsByAccountRow struct {
	ID              uuid.UUID   `json:"id"`
	AccountID       uuid.UUID   `json:"account_id"`
	TransactionType string      `json:"transaction_type"`
	Amount          string      `json:"amount"`
	Currency        string      `json:"currency"`
	Category        string      `json:"category"`
	Description     string      `json:"description"`
	HappenedAt      time.Time   `json:"happened_at"`
	CreatedAt       time.Time   `json:"created_at"`
	SystemTotalRate interface{} `json:"system_total_rate"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID uuid.UUID) ([]ListTransactionsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByAccountRow
	for rows.Next() {
		var i ListTransactionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.HappenedAt,
			&i.CreatedAt,
			&i.SystemTotalRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
