// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transactions_projection.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
    id, account_id, transaction_type, amount, currency, category, description, happened_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateTransactionParams struct {
	ID              uuid.UUID `json:"id"`
	AccountID       uuid.UUID `json:"account_id"`
	TransactionType string    `json:"transaction_type"`
	Amount          string    `json:"amount"`
	Currency        string    `json:"currency"`
	Category        string    `json:"category"`
	Description     string    `json:"description"`
	HappenedAt      time.Time `json:"happened_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.ID,
		arg.AccountID,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.HappenedAt,
	)
	return err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, transaction_type, amount, currency, category, description, happened_at, created_at FROM transactions
ORDER BY happened_at DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.HappenedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT id, account_id, transaction_type, amount, currency, category, description, happened_at, created_at FROM transactions
WHERE account_id = $1
ORDER BY happened_at DESC
`

func (q *Queries) ListTransactionsByAccount(ctx context.Context, accountID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.HappenedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
